name: compendium.terraform pipeline
on:
  push:
  pull_request:
    branches:
    - main
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
env:
  PACKAGE_NAME: Compendium.Terraform.nupkg
  ARTIFACT_NAME: Compendium.Terraform
defaults:
  run:
    shell: pwsh
jobs:
  SemanticVersion:
    runs-on: ubuntu-latest
    outputs:
      semantic_version: ${{ steps.semantic_release.outputs.SEMANTIC_VERSION }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        persist-credentials: false
    - name: Setup Node Version
      uses: actions/setup-node@master
      with:
        node-version: 18
    - name: Node Package Restore
      run: ./build/scripts/Install-NodePackages.ps1
    - name: Semantic Release (Dry-Run)
      id: semantic_release
      run: ./build/scripts/Invoke-SemanticRelease.ps1 -DryRun
      env:
        GH_TOKEN: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}
        GH_REF: ${{ github.ref }}
  Test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: pwsh
        working-directory: src/Compendium.Terraform/infrastructure
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        persist-credentials: false
    - name: terraform init
      run: ./../../../build/scripts/Initialize-Terraform.ps1 
    - name: terraform fmt
      run: ./../../../build/scripts/Test-TerraformFormat.ps1 
    - name: terraform validate
      run: ./../../../build/scripts/Test-Terraform.ps1 
    - name: terraform plan
      run: ./../../../build/scripts/Build-Terraform.ps1 -PlanName "terraform.tfplan"
      env:
        TF_VAR_contact: "someone@email.com"
    - name: terraform apply
      run: ./../../../build/scripts/Deploy-Terraform.ps1 -PlanName "terraform.tfplan"
  Build:
    runs-on: ubuntu-latest
    needs:
    - SemanticVersion
    - Test
    defaults:
      run:
        shell: pwsh
        working-directory: src
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - uses: nuget/setup-nuget@v1
      with:
        nuget-version: '6.5.0'
    - name: Package Template
      run: ./../build/scripts/Export-Package.ps1 -Nuspec "Compendium.Terraform.nuspec" -SemanticVersion "${{ needs.SemanticVersion.outputs.semantic_version }}"
    - name: Publish Artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.ARTIFACT_NAME }}
        path: src/Compendium.Terraform/${{ env.PACKAGE_NAME }}
  Release:
    if: ${{ github.ref == 'refs/heads/main' && github.event_name != 'pull_request' }}
    runs-on: ubuntu-latest
    needs:
    - SemanticVersion
    - Build
    defaults:
      run:
        shell: pwsh
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Download Artifact
      uses: actions/download-artifact@v3
      with:
        name: ${{ env.ARTIFACT_NAME }}
        path: a/${{ env.ARTIFACT_NAME }}
    - uses: nuget/setup-nuget@v1
      with:
        nuget-api-key: ${{ secrets.NUGETAPIKEY }}
        nuget-version: '6.5.0'
    - name: Setup Node Version
      uses: actions/setup-node@master
      with:
        node-version: 18
    - name: Node Package Restore
      run: ./build/scripts/Install-NodePackages.ps1
    - name: Semantic Release
      id: semantic_release
      run: ./build/scripts/Invoke-SemanticRelease.ps1
      env:
        GH_TOKEN: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}
        GH_REF: ${{ github.ref }}
    - name: Publish Module
      run: |
        ./build/scripts/Publish-Package.ps1 -PackagePath "src/Compendium.Terraform/${{ env.PACKAGE_NAME }}"
      env:
        NUGETSOURCE: ${{ vars.NUGETSOURCE }}
